// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB543zGjnJnhl7_-UlDYjl8VkNLkOiofxs',
    appId: '1:131604035065:web:e57e84f37fcbe8b00c7928',
    messagingSenderId: '131604035065',
    projectId: 'coffeebrain-acf97',
    authDomain: 'coffeebrain-acf97.firebaseapp.com',
    storageBucket: 'coffeebrain-acf97.appspot.com',
    measurementId: 'G-KCY6ZLDVQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5z3-P8NKmWivbZX_k7-l1T-_R9zMwrmc',
    appId: '1:131604035065:android:905d3b9e15480f400c7928',
    messagingSenderId: '131604035065',
    projectId: 'coffeebrain-acf97',
    storageBucket: 'coffeebrain-acf97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnfqTpR28k19y0AoI2ZpG4OybZfFnsbeY',
    appId: '1:131604035065:ios:533b4886bcbe42710c7928',
    messagingSenderId: '131604035065',
    projectId: 'coffeebrain-acf97',
    storageBucket: 'coffeebrain-acf97.appspot.com',
    androidClientId: '131604035065-p9k7j95oaqfbpmmam8uplhr37stno11j.apps.googleusercontent.com',
    iosClientId: '131604035065-5dpf82s5put2clebms5akpcgu3oluurg.apps.googleusercontent.com',
    iosBundleId: 'com.dushi.cofeebrain',
  );
}
